def CreateText(tc):
   	return {
		"QUESTION": "How much do the statement apply to you over the past week?",
		"I01": "I found myself getting upset by quite trivial things",
		"I02": "I was aware of dryness of my mouth",
		"I03": "I couldn't seem to experience any positive feeling at all",
		"I04": "I experienced breathing difficulty (eg, excessively rapid breathing, breathlessness in the absence of physical exertion)",
		"I05": "I just couldn't seem to get going",
		"I06": "I tended to over-react to situations",
		"I07": "I had a feeling of shakiness (eg, legs going to give way)",
		"I08": "I found it difficult to relax",
		"I09": "I found myself in situations that made me so anxious I was most relieved when they ended",
		"I10": "I felt that I had nothing to look forward to",
		"I11": "I found myself getting upset rather easily ",
		"I12": "I felt that I was using a lot of nervous energy",
		"I13": "I felt sad and depressed",
		"I14": "I found myself getting impatient when I was delayed in any way (for example, elevators, traffic lights, being kept waiting)",
		"I15": "I had a feeling of faintness",
		"I16": "I felt that I had lost interest in just about everything",
		"I17": "I felt I wasn't worth much as a person",
		"I18": "I felt that I was rather touchy",
		"I19": "I perspired noticeably (eg, hands sweaty) in the absence of high temperatures or physical exertion",
		"I20": "I felt scared without any good reason",
		"I21": "I felt that life wasn't worthwhile",
		"I22": "I found it hard to wind down ",
		"I23": "I had difficulty in swallowing",
		"I24": "I couldn't seem to get any enjoyment out of the things I did",
		"I25": "I was aware of the action of my heart in the absence of physical exertion (eg, sense of heart rate increase, heart missing a beat)",
		"I26": "I felt down-hearted and blue",
		"I27": "I found that I was very irritable",
		"I28": "I felt I was close to panic",
		"I29": "I found it hard to calm down after something upset me",
		"I30": "I feared that I would be \"thrown\" by some trivial but unfamiliar task",
		"I31": "I was unable to become enthusiastic about anything",
		"I32": "I found it difficult to tolerate interruptions to what I was doing",
		"I33": "I was in a state of nervous tension",
		"I34": "I felt I was pretty worthless",
		"I35": "I was intolerant of anything that kept me from getting on with what I was doing",
		"I36": "I felt terrified",
		"I37": "I could see nothing in the future to be hopeful about",
		"I38": "I felt that life was meaningless",
		"I39": "I found myself getting agitated",
		"I40": "I was worried about situations in which I might panic and make a fool of myself",
		"I41": "I experienced trembling (eg, in the hands)",
		"I42": "I found it difficult to work up the initiative to do things",
		"L0": "Did not apply to me at all",
		"L1": "Applied to me to some degree, or some of the time",
		"L2": "Applied to me to a considerable degree, or a good part of time",
		"L3": "Applied to me very much, or most of the time"
	}




